services:

  api:
    build: .
    container_name: fastapi_api
    ports:
      - 8000:8000
    env_file: .env
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  worker:
    build: .
    entrypoint: []
    container_name: celery_worker
    env_file: .env
    command: python -m celery -A app.queue.celery worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:alpine
    container_name: redis_cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
